import os, json, logging, requests
from datetime import datetime, timedelta, timezone
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

MAX_EVENTS  = int(os.getenv("MAX_EVENTS", 500))
DATA_DIR    = Path(__file__).parent.parent / "data"
OUTPUT_FILE = DATA_DIR / "events_clean.json"

def generate_demo_events():
    now = datetime.now(tz=timezone.utc)
    return [
        {"uid":"d001","title":"Concert Jazz au Sunset","description":"Soiree jazz avec le quartet Baptiste Trotignon au Sunset Sunside.","date_start":(now+timedelta(days=3)).isoformat(),"date_end":(now+timedelta(days=3)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Le Sunset Sunside","categories":"Musique","keywords":"jazz, concert","text":"Evenement : Concert Jazz au Sunset\nDescription : Soiree jazz intime avec Baptiste Trotignon.\nLieu : Le Sunset Sunside, Paris\nRegion : Ile-de-France\nCategorie : Musique"},
        {"uid":"d002","title":"Exposition Klimt - L Or et la Couleur","description":"Retrospective immersive de Klimt au Grand Palais Immersif avec projections geantes.","date_start":(now-timedelta(days=10)).isoformat(),"date_end":(now+timedelta(days=60)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Grand Palais Immersif","categories":"Exposition","keywords":"art, Klimt, exposition","text":"Evenement : Exposition Klimt\nDescription : Retrospective immersive au Grand Palais Immersif.\nLieu : Grand Palais Immersif, Paris\nRegion : Ile-de-France\nCategorie : Exposition"},
        {"uid":"d003","title":"Festival Solidays 2025","description":"Festival de musique sur l hippodrome de Longchamp, 3 jours, 70 artistes.","date_start":(now+timedelta(days=15)).isoformat(),"date_end":(now+timedelta(days=17)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Hippodrome de Longchamp","categories":"Festival","keywords":"festival, musique","text":"Evenement : Festival Solidays 2025\nDescription : 70 artistes a Longchamp.\nLieu : Hippodrome de Longchamp, Paris\nRegion : Ile-de-France\nCategorie : Festival"},
        {"uid":"d004","title":"Spectacle Corps Celestes - Danse contemporaine","description":"La compagnie Kafig presente Corps Celestes, hip-hop et danse contemporaine.","date_start":(now+timedelta(days=5)).isoformat(),"date_end":(now+timedelta(days=6)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Theatre National de Chaillot","categories":"Danse","keywords":"danse, contemporain","text":"Evenement : Corps Celestes\nDescription : Hip-hop et danse contemporaine a Chaillot.\nLieu : Theatre National de Chaillot, Paris\nRegion : Ile-de-France\nCategorie : Danse"},
        {"uid":"d005","title":"Nuit des Musees - Louvre gratuit","description":"Ouverture nocturne gratuite du Louvre avec visites guidees et ateliers.","date_start":(now+timedelta(days=8)).isoformat(),"date_end":(now+timedelta(days=8)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Musee du Louvre","categories":"Musee, Gratuit","keywords":"Louvre, gratuit, nuit musees","text":"Evenement : Nuit des Musees Louvre\nDescription : Ouverture nocturne gratuite avec visites guidees.\nLieu : Musee du Louvre, Paris\nRegion : Ile-de-France\nCategorie : Musee, Gratuit"},
        {"uid":"d006","title":"Atelier poterie enfants - Cite des Sciences","description":"Atelier creatif poterie pour enfants 6-12 ans a la Cite des Sciences.","date_start":(now+timedelta(days=2)).isoformat(),"date_end":(now+timedelta(days=2)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Cite des Sciences","categories":"Atelier, Jeunesse","keywords":"enfants, poterie, famille","text":"Evenement : Atelier poterie enfants\nDescription : Atelier creatif 6-12 ans a la Cite des Sciences.\nLieu : Cite des Sciences, Paris\nRegion : Ile-de-France\nCategorie : Atelier, Jeunesse"},
        {"uid":"d007","title":"Concert Philharmonie - Orchestre de Paris","description":"L Orchestre de Paris interprete la Symphonie n9 de Beethoven sous Klaus Makela.","date_start":(now+timedelta(days=12)).isoformat(),"date_end":(now+timedelta(days=12)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Philharmonie de Paris","categories":"Musique classique","keywords":"classique, Beethoven, Philharmonie","text":"Evenement : Concert Philharmonie\nDescription : Symphonie n9 Beethoven, Klaus Makela.\nLieu : Philharmonie de Paris, Paris\nRegion : Ile-de-France\nCategorie : Musique classique"},
        {"uid":"d008","title":"Marche artisanal Versailles","description":"Grand marche artisanal dans les jardins du Chateau de Versailles.","date_start":(now+timedelta(days=4)).isoformat(),"date_end":(now+timedelta(days=5)).isoformat(),"city":"Versailles","department":"Yvelines","region":"Ile-de-France","venue":"Chateau de Versailles","categories":"Artisanat","keywords":"artisanat, Versailles, famille","text":"Evenement : Marche artisanal Versailles\nDescription : Marche dans les jardins du Chateau de Versailles.\nLieu : Chateau de Versailles, Versailles, Yvelines\nRegion : Ile-de-France\nCategorie : Artisanat"},
        {"uid":"d009","title":"Cinema en plein air - Amelie Poulain","description":"Projection gratuite en plein air au Parc de la Villette, Amelie Poulain version 4K.","date_start":(now+timedelta(days=7)).isoformat(),"date_end":(now+timedelta(days=7)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Parc de la Villette","categories":"Cinema, Gratuit","keywords":"cinema, gratuit, plein air","text":"Evenement : Cinema en plein air Amelie Poulain\nDescription : Projection gratuite au Parc de la Villette.\nLieu : Parc de la Villette, Paris\nRegion : Ile-de-France\nCategorie : Cinema, Gratuit"},
        {"uid":"d010","title":"Conference IA et Art - Centre Pompidou","description":"Table ronde sur intelligence artificielle et creation artistique au Centre Pompidou.","date_start":(now+timedelta(days=20)).isoformat(),"date_end":(now+timedelta(days=20)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Centre Pompidou","categories":"Conference","keywords":"IA, art, conference","text":"Evenement : Conference IA et Art\nDescription : Table ronde IA et creation artistique au Centre Pompidou.\nLieu : Centre Pompidou, Paris\nRegion : Ile-de-France\nCategorie : Conference"},
        {"uid":"d011","title":"Escape Game - Musee d Orsay","description":"Experience immersive avec enigmes cachees dans les tableaux impressionnistes.","date_start":(now+timedelta(days=1)).isoformat(),"date_end":(now+timedelta(days=90)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Musee d Orsay","categories":"Jeu, Musee","keywords":"escape game, Orsay, insolite","text":"Evenement : Escape Game Musee d Orsay\nDescription : Enigmes dans les tableaux impressionnistes.\nLieu : Musee d Orsay, Paris\nRegion : Ile-de-France\nCategorie : Jeu, Musee"},
        {"uid":"d012","title":"Le Petit Prince - Theatre du Chatelet","description":"Adaptation theatrale du Petit Prince avec marionnettes et musique live pour toute la famille.","date_start":(now+timedelta(days=6)).isoformat(),"date_end":(now+timedelta(days=7)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Theatre du Chatelet","categories":"Theatre, Jeunesse","keywords":"theatre, enfants, famille","text":"Evenement : Le Petit Prince Theatre du Chatelet\nDescription : Marionnettes et musique live pour toute la famille.\nLieu : Theatre du Chatelet, Paris\nRegion : Ile-de-France\nCategorie : Theatre, Jeunesse"},
        {"uid":"d013","title":"Visite nocturne Catacombes de Paris","description":"Visite guidee nocturne des Catacombes, histoire secrete des galeries souterraines.","date_start":(now+timedelta(days=9)).isoformat(),"date_end":(now+timedelta(days=9)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"Catacombes de Paris","categories":"Visite, Histoire","keywords":"catacombes, nocturne, insolite","text":"Evenement : Visite nocturne Catacombes\nDescription : Visite guidee nocturne, histoire souterraine de Paris.\nLieu : Catacombes de Paris, Paris\nRegion : Ile-de-France\nCategorie : Visite, Histoire"},
        {"uid":"d014","title":"Open mic poesie et slam - La Maroquinerie","description":"Soiree open mic poesie et slam a La Maroquinerie, ouvert a tous, entree libre.","date_start":(now+timedelta(days=11)).isoformat(),"date_end":(now+timedelta(days=11)).isoformat(),"city":"Paris","department":"Paris","region":"Ile-de-France","venue":"La Maroquinerie","categories":"Poesie, Slam","keywords":"slam, poesie, gratuit","text":"Evenement : Open mic poesie La Maroquinerie\nDescription : Soiree slam et poesie ouverte a tous, entree libre.\nLieu : La Maroquinerie, Paris\nRegion : Ile-de-France\nCategorie : Poesie, Slam"},
        {"uid":"d015","title":"Marche de Noel Saint-Germain-en-Laye","description":"Marche de Noel traditionnel avec chalets artisanaux et animations enfants a Saint-Germain.","date_start":(now+timedelta(days=30)).isoformat(),"date_end":(now+timedelta(days=45)).isoformat(),"city":"Saint-Germain-en-Laye","department":"Yvelines","region":"Ile-de-France","venue":"Centre-ville","categories":"Marche, Fete","keywords":"Noel, marche, famille","text":"Evenement : Marche de Noel Saint-Germain-en-Laye\nDescription : Chalets artisanaux et animations enfants.\nLieu : Centre-ville, Saint-Germain-en-Laye, Yvelines\nRegion : Ile-de-France\nCategorie : Marche, Fete"},
    ]

def main():
    logger.info("=== Demarrage recuperation evenements ===")
    logger.info("Utilisation des donnees de demonstration (15 evenements IDF)")
    events = generate_demo_events()
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(events, f, ensure_ascii=False, indent=2)
    logger.info(f"Sauvegarde : {OUTPUT_FILE} ({len(events)} evenements)")
    logger.info("=== Termine ===")

if __name__ == "__main__":
    main()
